; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_g0b1re]
platform = ststm32
board = nucleo_g0b1re
framework = stm32cube
board_build.mcu = stm32g0b1rct6; change microcontroller
board_build.f_cpu = 64000000L; change MCU frequency
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
build_flags = -DG0
board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.system_file = yes
